---
title: "Maternal Depression and Antidepressant Use"
description: |
  Dr. Stephanie D'Souza on the Smooth Brain Society Podcast. My first time co-hosting + cheekily getting her to plug more stats education for psychology and policy folks.
name: Liza Bolton
date: 2024-09-17
preview: images/sahirs_image.png
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---

It was a real delight to be invited back to the [Smooth Brain Society](https://smoothbrainsociety.com/) by Sahir as a co-host for this fascinating episode with my friend and [COMPASS](https://www.auckland.ac.nz/en/arts/our-research/research-institutes-centres-groups/compass.html) colleague, Steph.

One of my (selfishly) favourite parts, lightly editted for the written word:

> Liza: If you were going to talk to that front row psych student in a first year course. What kind of advice would you give them, and why does it take more statistics? 

> Steph: Ooh, you're putting me on the spot, Liza. One thing I actually ask my policy students to do is to think about how statistics could help address policy problems. What is something that they're really passionate about, what is something they are interested in, what is something that they want to make a difference in, right? **And to be able to make a difference you need to have evidence** and that evidence can come from all perspectives as I see it. One thing with statistics is that you can make these generalizations and inferences if you've got good data. **So if there is something that's important to address in the population or in a community that you care about, it's really important to have that kind of representative, generalizable evidence.** And that's where statistics can come into play and help you. If you're wanting to advocate to the people at the top to make a difference, you need to have evidence there to show where the difference is needed and the impact is needed.

### Description

*There is often a tendency to focus on physical rather than mental health during pregnancy. While rates can vary by country, research suggests that about 10 - 20% of pregnant women experience depression during pregnancy. This is higher than the average rate of 6\% seen in the general population. The changes during pregnancy can also make it hard for mood disorders to be detected and treated. Dr. Stephanie D'Souza, PhD of The University of Auckland was on the podcast discussing her research into maternal depression and antidepressant use. Dr. Liza Bolton joins as co-host as we go through some of the key things to be aware of around maternal mental health and why research in this area is hard to undertake.*

### Watch or listen [1:17:50]

<iframe width="560" height="400" src="https://www.youtube.com/embed/QXpFoTKGVSg?si=SlXl23zZaoJwRx3e" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>


[Substack](https://smoothbrainsociety.substack.com/p/45-maternal-depression-and-antidepressant?utm_source=substack&utm_content=feed%3Arecommended%3Acopy_link)

[Spotify](https://open.spotify.com/episode/71bv61fDMDDnLfQ5V67NM0?si=61eb9d42542e4de0&nd=1&dlsi=fc58870089b142c0)

Details about my episode:  [*Lies, Damned Lies and Statistics*](https://www.lizabolton.com/talks.html#lies-damned-lies-and-statistics-smooth-brain-society).
