---
title: "Braiding Sweetgrass by Robin Wall Kimmerer"
description: |
  Links for Rohan Alexander's reading group.
preview: images/braiding-sweetgrass.jpeg
categories: 
  - books
author: Liza Bolton
date: 2021-06-25
output:
  distill::distill_article:
    toc: true
    toc_depth: 3
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Hi, I'm Liza. I'm a Settler Canadian, born here, but lived half my life in Aotearoa New Zealand on Tainui and then Ngāti Whatua lands and now back on 'Dish With One Spoon' treaty lands.

I'm really delighted that your group has been reading Braiding Sweetgrass, especially as June is National Indigenous History Month in Canada, so nicely done. But more importantly, you've been reading this as we learn more and more about the unmarked graves of Indigenous children at residential schools and perhaps grappling with what the upcoming Canada Day can or should mean to you.

Rohan invited me along to say hi because he knows I read this book because, a while back, I was up [tweeting at 3:00 a.m.](https://twitter.com/Liza_Bolton/status/1395643312552480768) about how I couldn't stop crying because of the story of the creation of Turtle Island. I certainly found the rest of the book more soothing than that.

I wanted to highlight an early quote on sweetgrass from the book that was a perfect preface to the experience I was about to have with the book itself and that I wonder if many of you also had.

> "Breathe in its scent and you start to remember things you didn’t know you’d forgotten"
>
> `r tufte::quote_footer('--- Robin Wall Kimmerer')`

This book reminded me of so many things I hadn't realized I'd forgotten and through stories connected my heart back up and not just my head. 15 months into a pandemic, in a new city I only moved to 18 months ago, I needed to connect back to life writ larger than just human life, to cycles of reciprocity and gratitude instead of news cycles. This book helped put my feet back on a path towards a balance I've been dearly missing. 

If these were some of the things you connected with to, I'd especially encourage you to learn more about the Dish With One Spoon agreement, as living here we are all invited to this treaty and in it you'll see much of what you may have found you'd forgotten when reading this book.

  --- <i class="fa fa-heart"></i> Liza

## Resources

### U of T

- [Reconciliation: Walking the Path of Indigenous Allyship June 30, 1:00-2:30 p.m. ET](https://www.lmp.utoronto.ca/event/reconciliation-walking-path-indigenous-allyship-june)
  - This workshop is run regularly, and is a good '101' session. Keep and eye out for it!
- [Land Acknowledgement (for U of T)](https://indigenous.utoronto.ca/about/land-acknowledgement/)
- Land acknowledgement workshops (TATP options)
  - I can't see when the next of these is planned, but it came highly recommended by my Head TA Becca Christensen. She opened our first TA trainings with a land acknowledgement.
- [Faculty of Arts and Science links](https://www.artsci.utoronto.ca/about/strategic-overview/indigenous-learning-knowledge)

### Indigenous Data Sovreignty

- Aotearoa New Zealand Data Sovereignty group: https://www.temanararaunga.maori.nz/
- Research Data Management: Indigenous Data Sovereignty (and OCAP® Ownership, Control Access, Possession) https://libguides.usask.ca/RDM/IndigenousDataSovereignty
  - OCAP trainings https://fnigc.ca/ocap-training/
- I'm still learning a lot about the Canadian context, but there is definitely a lot happening here!

### Dish With One Spoon

- Scroll down for a ~10 min video: https://facingcanada.facinghistory.org/the-dish-with-one-spoon-wampum

### More books

- [Settler: Identity and colonialism in 21st century Canada by Emma Battell Lowman and Adam J. Barker](https://fernwoodpublishing.ca/book/settler)
- [21 Things You May Not Know About the Indian Act by     Bob Joseph](https://www.ictinc.ca/books/21-things-you-may-not-know-about-the-indian-act)

### Twitter

Spend too much time on Twitter, crying at 3:00 a.m.? Or maybe at other times of day too? 

This list is obviously so woefully not comprehensive, but maybe just think of it as a prompt. *How are you seeking out and listening to Indigenous voices?*

- Bob Joseph, author [\@wewap](https://twitter.com/wewap)
- Robyn Rowe, health research & indigenous data sovereignty [\@RobynKRowe](https://twitter.com/RobynKRowe)
- Dr. Desi Small-Rodriguez, Assistant Professor of Sociology and American Indian Studies, UCLA [\@native4data](https://twitter.com/native4data)
- CBC Indigenous [\@CBCIndigenous](https://twitter.com/CBCIndigenous_
  - 'Meet some of the influencers of #NativeTwitter' https://www.cbc.ca/news/indigenous/indigenous-nativetwitter-influencers-1.4824534

### Other

- Teaching by the Medicine Wheel https://www.edcan.ca/articles/teaching-by-the-medicine-wheel/
- An Antidote to Dissatisfaction (spoiler: gratitude) https://www.youtube.com/watch?v=WPPPFqsECz0
- https://www.whose.land/en/


### Thanks

Thanks for inviting me, Rohan! And thank you to Paul for hosting.

If you are somehow reading this and _don't_ know Rohan, go fix that: 

<i class="fa fa-laptop"></i> [rohanalexander.com](https://rohanalexander.com/) & <i class="fa fa-twitter"></i> [\@RohanAlexander](https://twitter.com/RohanAlexander)